[package]
name = "read-osm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.7"
osmpbfreader = "0.16.1"
reqwest = { version = "0.11.23", features = ["blocking"] }
